[package]
edition = "2021"
name = "bonsai-trie"
version = "0.1.0"

[features]
default = ["std", "rocksdb"]
rocksdb = ["dep:rocksdb"]
std = [
  "parity-scale-codec/std",
  "bitvec/std",
  "starknet-types-core/std",
  "rayon",
  "hashbrown/rayon",
]
# internal
bench = []

[dependencies]
bitvec = { version = "1", default-features = false, features = ["alloc"] }
derive_more = { version = "0.99.17", default-features = false, features = [
  "constructor",
] }
hashbrown = "0.14.3"
log = "0.4.20"
rayon = { version = "1.9.0", optional = true }
smallvec = { version = "1.11.2", features = ["serde"] }
slotmap = "1.0.7"

parity-scale-codec = { version = "3.0.0", default-features = false, features = [
  "derive",
] }
serde = { version = "1.0.195", default-features = false, features = [
  "derive",
  "alloc",
] }
starknet-types-core = { version = "0.1.5", default-features = false, features = [
  "hash",
  "parity-scale-codec",
  "alloc",
] }

# Optionals
rocksdb = { optional = true, version = "0.21.0", features = [
  "multi-threaded-cf",
] }

[dev-dependencies]
env_logger = "0.11.3"
once_cell = "1.19.0"
pprof = { version = "0.3", features = ["flamegraph"] }
rand = { version = "0.8.5", features = ["small_rng"] }
tempfile = "3.8.0"
rstest = "0.18.2"
test-log = "0.2.15"
indexmap = "2.2.6"
criterion = "0.5.1"
proptest = "1.4.0"
proptest-derive = "0.4.0"
serde_json = "1.0.68"

[[bench]]
name = "storage"
required-features = ["bench"]
harness = false
